### PR TITLE
corrected switch titleId numbers

### PR DESCRIPTION
**Pull request by HGStone**

### CODE REVIEW

**Comment by NiceneNerd** [comment]
What's the `01007EF00011E800`? I've never seen it before. Does BCML use it?

Also, I've seen at least 4 different versions of the DLC title ID(s). Do you know what the deal with those is?

**Comment by HGStone** [comment]
yes bcml uses it.. that is the Base with update for version 1.6.0 of botw.. and i have only seen 2 title id for the DLC.. but only one is ever used.. the other one only contains a txt file

**Comment by HGStone** [comment]
i guess i should clarify.. the base/update dump is labeled 01007EF00011E800 but the switch expects to have 01007EF00011E000 in atmosphere/contents

**Comment by NiceneNerd** [comment]
That is very clarifying indeed.

**Pull request merged**
